### ISSUE TITLE
push mgi-merged.gaf (silver-issue-325-gopreprocess) up to the mirror when successful 

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/gopreprocess#65] opened 2024-03-21 17:56 UTC
- [ ] change the name to `mgi-p2go-homology.gaf` 
- [ ] push to the bucket - only have to worry about updates, no deletes necessary.  file is not versioned. 
- [ ] rename silver-issue-325-gopreprocess pipeline to something more intuitive

go look at the go-copy-to-mirror pipeline branch for finding the S3 bucket.

**Comment by kltm** [comment] 2024-04-04 01:14
Now dupe of https://github.com/geneontology/pipeline/issues/369

**Closed by kltm** 2024-04-04 01:14 UTC
